language: node_js
node_js:
    - "6.4.0"
service:
    - mysql
install:
    - "npm install"
    - "export TRAVIS=1"
before_script:
    - npm install -g mocha
    - npm install -g babel-cli
    - mysql -e 'create database user_app_staging;'

